name: Release Diagram
on:
  push:
    branches:
      - master
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PlantUML
        run: sudo apt-get install -y plantuml
      - name: Render Diagram
        run: plantuml -tsvg schema.puml
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: schema.svg
